In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\user\.conda\envs\yolo\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\user\.conda\envs\yolo\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\.conda\envs\yolo\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\.conda\envs\yolo\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\.conda\envs\yolo\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\.conda\envs\yolo\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os  # Import the os module to interact with the operating system
from glob import glob  # Import glob to find all pathnames matching a specified pattern
import pandas as pd  # Import pandas for data manipulation and analysis
from xml.etree import ElementTree as et  # Import ElementTree for parsing XML data
from functools import reduce  # Import reduce to apply a function cumulatively to items in an iterable

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
# step-1: get path of each xml file
xmlfiles = glob('./data_images/*.xml')
xmlfiles

['./data_images\\aa.xml',
 './data_images\\image_1 (2).xml',
 './data_images\\image_1 (3).xml',
 './data_images\\image_1 (5).xml',
 './data_images\\image_1 (6).xml',
 './data_images\\image_1 (7).xml',
 './data_images\\image_1 (8).xml',
 './data_images\\image_1.xml',
 './data_images\\image_10 (3).xml',
 './data_images\\image_10 (4).xml',
 './data_images\\image_10 (5).xml',
 './data_images\\image_10 (6).xml',
 './data_images\\image_10 (7).xml',
 './data_images\\image_10 (8).xml',
 './data_images\\image_10.xml',
 './data_images\\image_11 (2).xml',
 './data_images\\image_11 (3).xml',
 './data_images\\image_11 (4).xml',
 './data_images\\image_11 (5).xml',
 './data_images\\image_11 (6).xml',
 './data_images\\image_11 (7).xml',
 './data_images\\image_11.xml',
 './data_images\\image_12 (2).xml',
 './data_images\\image_12 (4).xml',
 './data_images\\image_12 (5).xml',
 './data_images\\image_12 (6).xml',
 './data_images\\image_12 (7).xml',
 './data_images\\image_13 (3).xml',
 './data_images\\image_13 (4).xml',
 './data_images\\image_13 (7).xml',
 './data_images\\image_14 (2).xml',
 './data_images\\image_14 (3).xml',
 './data_images\\image_14 (4).xml',
 './data_images\\image_14 (5).xml',
 './data_images\\image_14 (6).xml',
 './data_images\\image_14.xml',
 './data_images\\image_15 (3).xml',
 './data_images\\image_15 (4).xml',
 './data_images\\image_15 (5).xml',
 './data_images\\image_15 (6).xml',
 './data_images\\image_15 (7).xml',
 './data_images\\image_16 (3).xml',
 './data_images\\image_16 (4).xml',
 './data_images\\image_16 (5).xml',
 './data_images\\image_16 (6).xml',
 './data_images\\image_16 (8).xml',
 './data_images\\image_16.xml',
 './data_images\\image_17 (2).xml',
 './data_images\\image_17 (3).xml',
 './data_images\\image_17 (4).xml',
 './data_images\\image_17 (5).xml',
 './data_images\\image_17 (6).xml',
 './data_images\\image_17 (7).xml',
 './data_images\\image_17 (8).xml',
 './data_images\\image_17.xml',
 './data_images\\image_18 (2).xml',
 './data_images\\image_18 (3).xml',
 './data_images\\image_18 (4).xml',
 './data_images\\image_18 (5).xml',
 './data_images\\image_18 (6).xml',
 './data_images\\image_18 (7).xml',
 './data_images\\image_18 (8).xml',
 './data_images\\image_18.xml',
 './data_images\\image_19 (2).xml',
 './data_images\\image_19 (3).xml',
 './data_images\\image_19 (6).xml',
 './data_images\\image_19 (7).xml',
 './data_images\\image_2 (2).xml',
 './data_images\\image_2 (4).xml',
 './data_images\\image_2 (5).xml',
 './data_images\\image_2 (6).xml',
 './data_images\\image_2 (7).xml',
 './data_images\\image_2 (8).xml',
 './data_images\\image_2.xml',
 './data_images\\image_20 (2).xml',
 './data_images\\image_20 (3).xml',
 './data_images\\image_20 (4).xml',
 './data_images\\image_20 (5).xml',
 './data_images\\image_20 (6).xml',
 './data_images\\image_20 (8).xml',
 './data_images\\image_20.xml',
 './data_images\\image_21 (3).xml',
 './data_images\\image_21 (4).xml',
 './data_images\\image_21 (5).xml',
 './data_images\\image_21 (6).xml',
 './data_images\\image_21 (7).xml',
 './data_images\\image_21 (8).xml',
 './data_images\\image_21.xml',
 './data_images\\image_22 (2).xml',
 './data_images\\image_22 (3).xml',
 './data_images\\image_22 (4).xml',
 './data_images\\image_22 (5).xml',
 './data_images\\image_22 (6).xml',
 './data_images\\image_22 (7).xml',
 './data_images\\image_22 (8).xml',
 './data_images\\image_22.xml',
 './data_images\\image_23 (2).xml',
 './data_images\\image_23 (3).xml',
 './data_images\\image_23 (4).xml',
 './data_images\\image_23 (5).xml',
 './data_images\\image_23 (6).xml',
 './data_images\\image_23 (7).xml',
 './data_images\\image_23 (8).xml',
 './data_images\\image_23.xml',
 './data_images\\image_24 (2)(1).xml',
 './data_images\\image_24 (2).xml',
 './data_images\\image_24 (3)(1).xml',
 './data_images\\image_24 (3).xml',
 './data_images\\image_24 (5)(1).xml',
 './data_images\\image_24 (5).xml',
 './data_images\\image_24 (6)(1).xml',
 './data_images\\image_24 (6).xml',
 './data_images\\image_24 (7)(1).xml',
 './data_images\\image_24 (7).xml',
 './data_images\\image_24 (8)(1).xml',
 './data_images\\image_24 (8).xml']

In [5]:
def extract_text(filename):
    tree = et.parse(filename)
    root = tree.getroot()

    # Extract filename, width, and height
    image_name = root.find('filename').text if root.find('filename') is not None else None
    width = root.find('size/width').text if root.find('size/width') is not None else None
    height = root.find('size/height').text if root.find('size/height') is not None else None
    
    parser = []
    for obj in root.findall('object'):
        name = obj.find('name').text if obj.find('name') is not None else None
        bndbox = obj.find('bndbox')
        if bndbox is not None:
            xmin = bndbox.find('xmin').text if bndbox.find('xmin') is not None else None
            xmax = bndbox.find('xmax').text if bndbox.find('xmax') is not None else None
            ymin = bndbox.find('ymin').text if bndbox.find('ymin') is not None else None
            ymax = bndbox.find('ymax').text if bndbox.find('ymax') is not None else None
        else:
            xmin = xmax = ymin = ymax = None
        
        parser.append([image_name, width, height, name, xmin, xmax, ymin, ymax])
        
    return parser

In [6]:
parser_all = list(map(extract_text,xmlfiles))
parser_all

[[['image_31 (6).jpg', '1024', '768', 'horse', '252', '757', '148', '636']],
 [['image_1 (2).jpg', '1024', '819', 'bottle', '250', '467', '65', '819'],
  ['image_1 (2).jpg', '1024', '819', 'bottle', '546', '748', '60', '791'],
  ['image_1 (2).jpg', '1024', '819', 'bottle', '444', '614', '190', '812']],
 [['image_1 (3).jpg', '1024', '682', 'bus', '54', '994', '59', '548']],
 [['image_1 (5).jpg', '700', '616', 'horse', '112', '614', '21', '581']],
 [['image_1 (6).jpg', '1024', '683', 'person', '181', '492', '75', '504'],
  ['image_1 (6).jpg', '1024', '683', 'person', '627', '984', '59', '446']],
 [['image_1 (7).jpg', '239', '127', 'sofa', '2', '237', '4', '124']],
 [['image_1 (8).jpg', '1024', '768', 'table', '9', '958', '131', '715']],
 [['image_1.jpg', '1024', '742', 'bird', '407', '646', '203', '677']],
 [['image_10 (3).jpg', '1024', '576', 'bus', '83', '998', '94', '492']],
 [['image_10 (4).jpg', '1000', '813', 'chair', '240', '893', '55', '761']],
 [['image_10 (5).jpg', '500', '333', 'horse', '11', '290', '1', '330'],
  ['image_10 (5).jpg', '500', '333', 'horse', '295', '500', '18', '333']],
 [['image_10 (6).jpg', '1024', '683', 'person', '21', '464', '69', '683'],
  ['image_10 (6).jpg', '1024', '683', 'person', '664', '1019', '109', '683']],
 [['image_10 (7).jpg', '1024', '768', 'sofa', '10', '1024', '80', '660']],
 [['image_10 (8).jpg', '1024', '683', 'table', '95', '939', '145', '632']],
 [['image_10.jpg', '683', '1024', 'bird', '16', '683', '50', '1012']],
 [['image_11 (2).jpg', '531', '800', 'bottle', '81', '493', '67', '751']],
 [['image_11 (3).jpg', '1024', '768', 'bus', '2', '778', '203', '631']],
 [['image_11 (4).jpg', '300', '450', 'chair', '3', '300', '12', '424']],
 [['image_11 (5).jpg', '1023', '685', 'horse', '152', '1023', '25', '685']],
 [['image_11 (6).jpg', '683', '1024', 'person', '241', '501', '283', '939'],
  ['image_11 (6).jpg', '683', '1024', 'person', '34', '258', '295', '954']],
 [['image_11 (7).jpg', '1024', '681', 'sofa', '119', '984', '102', '653']],
 [['image_11.jpg', '1024', '680', 'person', '214', '508', '242', '638'],
  ['image_11.jpg', '1024', '680', 'person', '594', '806', '261', '662'],
  ['image_11.jpg', '1024', '680', 'bottle', '848', '897', '503', '639'],
  ['image_11.jpg', '1024', '680', 'cycle', '227', '781', '12', '301']],
 [['image_12 (2).jpg', '682', '1024', 'bottle', '102', '600', '61', '996']],
 [['image_12 (4).jpg', '360', '480', 'chair', '38', '339', '10', '480']],
 [['image_12 (5).jpg', '1024', '683', 'horse', '103', '660', '81', '683']],
 [['image_12 (6).jpg', '1023', '681', 'person', '315', '918', '34', '673']],
 [['image_12 (7).jpg', '1024', '768', 'sofa', '33', '1024', '90', '764']],
 [['image_13 (3).jpg', '683', '1024', 'bus', '58', '683', '165', '901']],
 [['image_13 (4).jpg', '683', '1024', 'chair', '107', '609', '39', '983']],
 [['image_13 (7).jpg', '765', '1024', 'sofa', '18', '723', '282', '941']],
 [['image_14 (2).jpg', '960', '673', 'bottle', '166', '369', '54', '569'],
  ['image_14 (2).jpg', '960', '673', 'bottle', '615', '815', '8', '648']],
 [['image_14 (3).jpg', '1024', '768', 'bus', '35', '195', '292', '490'],
  ['image_14 (3).jpg', '1024', '768', 'bus', '425', '960', '38', '666']],
 [['image_14 (4).jpg', '1024', '830', 'car', '65', '1017', '229', '775']],
 [['image_14 (5).jpg', '314', '523', 'table', '12', '299', '16', '518']],
 [['image_14 (6).jpg', '924', '663', 'horse', '1', '537', '26', '657']],
 [['image_14.jpg', '1024', '637', 'person', '284', '624', '202', '602'],
  ['image_14.jpg', '1024', '637', 'cycle', '758', '981', '186', '576'],
  ['image_14.jpg', '1024', '637', 'sofa', '139', '828', '302', '551']],
 [['image_15 (3).jpg', '1024', '681', 'bus', '447', '944', '157', '545']],
 [['image_15 (4).jpg', '866', '577', 'car', '382', '866', '68', '576']],
 [['image_15 (5).jpg', '426', '640', 'chair', '41', '380', '87', '558']],
 [['image_15 (6).jpg', '1024', '700', 'horse', '3', '582', '53', '671'],
  ['image_15 (6).jpg', '1024', '700', 'horse', '526', '1006', '59', '633']],
 [['image_15 (7).jpg', '1024', '768', 'person', '10', '496', '12', '652'],
  ['image_15 (7).jpg', '1024', '768', 'person', '582', '1024', '107', '768']],
 [['image_16 (3).jpg', '1023', '685', 'bus', '213', '1023', '112', '575']],
 [['image_16 (4).jpg', '1023', '685', 'car', '18', '983', '111', '618']],
 [['image_16 (5).jpg', '532', '800', 'chair', '16', '486', '50', '786']],
 [['image_16 (6).jpg', '683', '1024', 'horse', '4', '567', '119', '869']],
 [['image_16 (8).jpg', '1024', '768', 'sofa', '13', '1024', '166', '629']],
 [['image_16.jpg', '1024', '683', 'chair', '399', '889', '363', '646'],
  ['image_16.jpg', '1024', '683', 'sofa', '675', '996', '261', '392']],
 [['image_17 (2).jpg', '1024', '681', 'bottle', '133', '322', '214', '616'],
  ['image_17 (2).jpg', '1024', '681', 'bottle', '424', '608', '199', '605'],
  ['image_17 (2).jpg', '1024', '681', 'bottle', '747', '968', '124', '605']],
 [['image_17 (3).jpg', '1023', '577', 'bus', '79', '693', '76', '539']],
 [['image_17 (4).jpg', '1024', '768', 'car', '28', '887', '92', '615']],
 [['image_17 (5).jpg', '747', '1024', 'chair', '95', '560', '115', '992']],
 [['image_17 (6).jpg', '200', '150', 'horse', '4', '189', '6', '140']],
 [['image_17 (7).jpg', '1024', '1024', 'person', '216', '327', '419', '670'],
  ['image_17 (7).jpg', '1024', '1024', 'person', '334', '424', '459', '659']],
 [['image_17 (8).jpg', '640', '480', 'sofa', '2', '640', '66', '435']],
 [['image_17.jpg', '1024', '576', 'person', '595', '799', '48', '430']],
 [['image_18 (2).jpg', '680', '1024', 'bottle', '118', '547', '67', '994']],
 [['image_18 (3).jpg', '1024', '683', 'bus', '193', '889', '90', '585']],
 [['image_18 (4).jpg', '1024', '683', 'car', '33', '995', '156', '630']],
 [['image_18 (5).jpg', '768', '1024', 'chair', '118', '627', '148', '970']],
 [['image_18 (6).jpg', '1024', '1024', 'horse', '75', '827', '3', '1010']],
 [['image_18 (7).jpg', '1024', '684', 'person', '311', '546', '73', '344'],
  ['image_18 (7).jpg', '1024', '684', 'car', '84', '909', '221', '577']],
 [['image_18 (8).jpg', '1024', '768', 'sofa', '71', '936', '108', '660']],
 [['image_18.jpg', '682', '1023', 'person', '284', '531', '256', '594'],
  ['image_18.jpg', '682', '1023', 'cycle', '130', '486', '454', '737']],
 [['image_19 (2).jpg', '787', '1024', 'bottle', '57', '430', '65', '864'],
  ['image_19 (2).jpg', '787', '1024', 'bottle', '430', '744', '86', '887']],
 [['image_19 (3).jpg', '800', '600', 'bus', '7', '792', '66', '505']],
 [['image_19 (6).jpg', '1024', '683', 'horse', '493', '927', '179', '566']],
 [['image_19 (7).jpg', '1024', '683', 'car', '108', '154', '450', '495']],
 [['image_2 (2).jpg', '1024', '768', 'bottle', '260', '509', '157', '587'],
  ['image_2 (2).jpg', '1024', '768', 'bottle', '542', '795', '136', '581']],
 [['image_2 (4).jpg', '685', '1023', 'chair', '282', '665', '205', '964']],
 [['image_2 (5).jpg', '1024', '682', 'horse', '273', '1024', '78', '682']],
 [['image_2 (6).jpg', '683', '1024', 'person', '201', '542', '40', '720']],
 [['image_2 (7).jpg', '1024', '768', 'sofa', '13', '791', '183', '759'],
  ['image_2 (7).jpg', '1024', '768', 'plant', '863', '1024', '164', '544']],
 [['image_2 (8).jpg', '1024', '1024', 'chair', '12', '398', '473', '1005'],
  ['image_2 (8).jpg', '1024', '1024', 'chair', '422', '820', '485', '989'],
  ['image_2 (8).jpg', '1024', '1024', 'chair', '817', '996', '419', '876'],
  ['image_2 (8).jpg', '1024', '1024', 'glass', '305', '372', '312', '483'],
  ['image_2 (8).jpg', '1024', '1024', 'table', '18', '1004', '295', '941']],
 [['image_2.jpg', '1024', '683', 'bird', '427', '708', '217', '508']],
 [['image_20 (2).jpg', '595', '1024', 'bottle', '175', '425', '4', '1003']],
 [['image_20 (3).jpg', '1000', '750', 'bus', '41', '750', '226', '634']],
 [['image_20 (4).jpg', '800', '533', 'car', '62', '719', '105', '447']],
 [['image_20 (5).jpg', '768', '1024', 'chair', '79', '629', '20', '978']],
 [['image_20 (6).jpg', '1024', '768', 'horse', '35', '890', '81', '645']],
 [['image_20 (8).jpg', '1024', '768', 'sofa', '9', '1000', '177', '724']],
 [['image_20.jpg', '1024', '683', 'person', '638', '789', '220', '660']],
 [['image_21 (3).jpg', '1024', '576', 'bus', '196', '851', '111', '494']],
 [['image_21 (4).jpg', '1024', '683', 'car', '101', '901', '172', '617'],
  ['image_21 (4).jpg', '1024', '683', 'person', '1', '81', '208', '519']],
 [['image_21 (5).jpg', '532', '800', 'chair', '68', '516', '12', '800']],
 [['image_21 (6).jpg', '1024', '683', 'person', '525', '657', '93', '326'],
  ['image_21 (6).jpg', '1024', '683', 'horse', '365', '819', '102', '560'],
  ['image_21 (6).jpg', '1024', '683', 'car', '806', '1024', '204', '449']],
 [['image_21 (7).jpg', '1024', '683', 'person', '382', '612', '41', '490'],
  ['image_21 (7).jpg', '1024', '683', 'cycle', '288', '777', '321', '680']],
 [['image_21 (8).jpg', '1024', '768', 'sofa', '1', '1024', '172', '656']],
 [['image_21.jpg', '1024', '576', 'cycle', '566', '987', '101', '420']],
 [['image_22 (2).jpg', '635', '1024', 'bottle', '157', '491', '6', '1017']],
 [['image_22 (3).jpg', '1024', '576', 'bus', '214', '775', '39', '543']],
 [['image_22 (4).jpg', '1024', '768', 'car', '97', '882', '145', '641']],
 [['image_22 (5).jpg', '613', '1023', 'chair', '81', '557', '5', '983']],
 [['image_22 (6).jpg', '1024', '681', 'horse', '4', '972', '14', '675']],
 [['image_22 (7).jpg', '683', '1024', 'person', '139', '379', '240', '784']],
 [['image_22 (8).jpg', '1024', '572', 'person', '40', '995', '86', '362'],
  ['image_22 (8).jpg', '1024', '572', 'sofa', '3', '1023', '13', '546']],
 [['image_22.jpg', '1024', '605', 'cycle', '614', '868', '413', '563']],
 [['image_23 (2).jpg', '681', '1024', 'bottle', '22', '329', '63', '932'],
  ['image_23 (2).jpg', '681', '1024', 'bottle', '338', '649', '164', '955']],
 [['image_23 (3).jpg', '1024', '768', 'bus', '1', '997', '239', '756']],
 [['image_23 (4).jpg', '1024', '683', 'car', '275', '807', '184', '665']],
 [['image_23 (5).jpg', '1024', '768', 'chair', '186', '746', '19', '766']],
 [['image_23 (6).jpg', '1024', '683', 'horse', '81', '627', '17', '683']],
 [['image_23 (7).jpg', '1024', '790', 'car', '36', '778', '192', '786'],
  ['image_23 (7).jpg', '1024', '790', 'person', '876', '977', '319', '605']],
 [['image_23 (8).jpg', '1024', '768', 'sofa', '25', '1024', '94', '593']],
 [['image_23.jpg', '1024', '683', 'person', '304', '825', '79', '683'],
  ['image_23.jpg', '1024', '683', 'bottle', '860', '935', '327', '476']],
 [['image_24 (2).jpg', '1024', '683', 'bottle', '362', '612', '59', '641']],
 [['image_24 (2).jpg', '1024', '683', 'bottle', '362', '612', '59', '641']],
 [['image_24 (3).jpg', '1024', '682', 'bus', '360', '882', '52', '626']],
 [['image_24 (3).jpg', '1024', '682', 'bus', '360', '882', '52', '626']],
 [['image_24 (5).jpg', '680', '1024', 'chair', '120', '598', '191', '884']],
 [['image_24 (5).jpg', '680', '1024', 'chair', '120', '598', '191', '884']],
 [['image_24 (6).jpg', '1024', '680', 'horse', '341', '1024', '28', '680']],
 [['image_24 (6).jpg', '1024', '680', 'horse', '341', '1024', '28', '680']],
 [['image_24 (7).jpg', '1024', '660', 'person', '407', '629', '53', '660']],
 [['image_24 (7).jpg', '1024', '660', 'person', '407', '629', '53', '660']],
 [['image_24 (8).jpg', '1024', '768', 'sofa', '1', '1024', '60', '529']],
 [['image_24 (8).jpg', '1024', '768', 'sofa', '1', '1024', '60', '529']]]

In [7]:
data = reduce(lambda x, y : x+y,parser_all)
data

[['image_31 (6).jpg', '1024', '768', 'horse', '252', '757', '148', '636'],
 ['image_1 (2).jpg', '1024', '819', 'bottle', '250', '467', '65', '819'],
 ['image_1 (2).jpg', '1024', '819', 'bottle', '546', '748', '60', '791'],
 ['image_1 (2).jpg', '1024', '819', 'bottle', '444', '614', '190', '812'],
 ['image_1 (3).jpg', '1024', '682', 'bus', '54', '994', '59', '548'],
 ['image_1 (5).jpg', '700', '616', 'horse', '112', '614', '21', '581'],
 ['image_1 (6).jpg', '1024', '683', 'person', '181', '492', '75', '504'],
 ['image_1 (6).jpg', '1024', '683', 'person', '627', '984', '59', '446'],
 ['image_1 (7).jpg', '239', '127', 'sofa', '2', '237', '4', '124'],
 ['image_1 (8).jpg', '1024', '768', 'table', '9', '958', '131', '715'],
 ['image_1.jpg', '1024', '742', 'bird', '407', '646', '203', '677'],
 ['image_10 (3).jpg', '1024', '576', 'bus', '83', '998', '94', '492'],
 ['image_10 (4).jpg', '1000', '813', 'chair', '240', '893', '55', '761'],
 ['image_10 (5).jpg', '500', '333', 'horse', '11', '290', '1', '330'],
 ['image_10 (5).jpg', '500', '333', 'horse', '295', '500', '18', '333'],
 ['image_10 (6).jpg', '1024', '683', 'person', '21', '464', '69', '683'],
 ['image_10 (6).jpg', '1024', '683', 'person', '664', '1019', '109', '683'],
 ['image_10 (7).jpg', '1024', '768', 'sofa', '10', '1024', '80', '660'],
 ['image_10 (8).jpg', '1024', '683', 'table', '95', '939', '145', '632'],
 ['image_10.jpg', '683', '1024', 'bird', '16', '683', '50', '1012'],
 ['image_11 (2).jpg', '531', '800', 'bottle', '81', '493', '67', '751'],
 ['image_11 (3).jpg', '1024', '768', 'bus', '2', '778', '203', '631'],
 ['image_11 (4).jpg', '300', '450', 'chair', '3', '300', '12', '424'],
 ['image_11 (5).jpg', '1023', '685', 'horse', '152', '1023', '25', '685'],
 ['image_11 (6).jpg', '683', '1024', 'person', '241', '501', '283', '939'],
 ['image_11 (6).jpg', '683', '1024', 'person', '34', '258', '295', '954'],
 ['image_11 (7).jpg', '1024', '681', 'sofa', '119', '984', '102', '653'],
 ['image_11.jpg', '1024', '680', 'person', '214', '508', '242', '638'],
 ['image_11.jpg', '1024', '680', 'person', '594', '806', '261', '662'],
 ['image_11.jpg', '1024', '680', 'bottle', '848', '897', '503', '639'],
 ['image_11.jpg', '1024', '680', 'cycle', '227', '781', '12', '301'],
 ['image_12 (2).jpg', '682', '1024', 'bottle', '102', '600', '61', '996'],
 ['image_12 (4).jpg', '360', '480', 'chair', '38', '339', '10', '480'],
 ['image_12 (5).jpg', '1024', '683', 'horse', '103', '660', '81', '683'],
 ['image_12 (6).jpg', '1023', '681', 'person', '315', '918', '34', '673'],
 ['image_12 (7).jpg', '1024', '768', 'sofa', '33', '1024', '90', '764'],
 ['image_13 (3).jpg', '683', '1024', 'bus', '58', '683', '165', '901'],
 ['image_13 (4).jpg', '683', '1024', 'chair', '107', '609', '39', '983'],
 ['image_13 (7).jpg', '765', '1024', 'sofa', '18', '723', '282', '941'],
 ['image_14 (2).jpg', '960', '673', 'bottle', '166', '369', '54', '569'],
 ['image_14 (2).jpg', '960', '673', 'bottle', '615', '815', '8', '648'],
 ['image_14 (3).jpg', '1024', '768', 'bus', '35', '195', '292', '490'],
 ['image_14 (3).jpg', '1024', '768', 'bus', '425', '960', '38', '666'],
 ['image_14 (4).jpg', '1024', '830', 'car', '65', '1017', '229', '775'],
 ['image_14 (5).jpg', '314', '523', 'table', '12', '299', '16', '518'],
 ['image_14 (6).jpg', '924', '663', 'horse', '1', '537', '26', '657'],
 ['image_14.jpg', '1024', '637', 'person', '284', '624', '202', '602'],
 ['image_14.jpg', '1024', '637', 'cycle', '758', '981', '186', '576'],
 ['image_14.jpg', '1024', '637', 'sofa', '139', '828', '302', '551'],
 ['image_15 (3).jpg', '1024', '681', 'bus', '447', '944', '157', '545'],
 ['image_15 (4).jpg', '866', '577', 'car', '382', '866', '68', '576'],
 ['image_15 (5).jpg', '426', '640', 'chair', '41', '380', '87', '558'],
 ['image_15 (6).jpg', '1024', '700', 'horse', '3', '582', '53', '671'],
 ['image_15 (6).jpg', '1024', '700', 'horse', '526', '1006', '59', '633'],
 ['image_15 (7).jpg', '1024', '768', 'person', '10', '496', '12', '652'],
 ['image_15 (7).jpg', '1024', '768', 'person', '582', '1024', '107', '768'],
 ['image_16 (3).jpg', '1023', '685', 'bus', '213', '1023', '112', '575'],
 ['image_16 (4).jpg', '1023', '685', 'car', '18', '983', '111', '618'],
 ['image_16 (5).jpg', '532', '800', 'chair', '16', '486', '50', '786'],
 ['image_16 (6).jpg', '683', '1024', 'horse', '4', '567', '119', '869'],
 ['image_16 (8).jpg', '1024', '768', 'sofa', '13', '1024', '166', '629'],
 ['image_16.jpg', '1024', '683', 'chair', '399', '889', '363', '646'],
 ['image_16.jpg', '1024', '683', 'sofa', '675', '996', '261', '392'],
 ['image_17 (2).jpg', '1024', '681', 'bottle', '133', '322', '214', '616'],
 ['image_17 (2).jpg', '1024', '681', 'bottle', '424', '608', '199', '605'],
 ['image_17 (2).jpg', '1024', '681', 'bottle', '747', '968', '124', '605'],
 ['image_17 (3).jpg', '1023', '577', 'bus', '79', '693', '76', '539'],
 ['image_17 (4).jpg', '1024', '768', 'car', '28', '887', '92', '615'],
 ['image_17 (5).jpg', '747', '1024', 'chair', '95', '560', '115', '992'],
 ['image_17 (6).jpg', '200', '150', 'horse', '4', '189', '6', '140'],
 ['image_17 (7).jpg', '1024', '1024', 'person', '216', '327', '419', '670'],
 ['image_17 (7).jpg', '1024', '1024', 'person', '334', '424', '459', '659'],
 ['image_17 (8).jpg', '640', '480', 'sofa', '2', '640', '66', '435'],
 ['image_17.jpg', '1024', '576', 'person', '595', '799', '48', '430'],
 ['image_18 (2).jpg', '680', '1024', 'bottle', '118', '547', '67', '994'],
 ['image_18 (3).jpg', '1024', '683', 'bus', '193', '889', '90', '585'],
 ['image_18 (4).jpg', '1024', '683', 'car', '33', '995', '156', '630'],
 ['image_18 (5).jpg', '768', '1024', 'chair', '118', '627', '148', '970'],
 ['image_18 (6).jpg', '1024', '1024', 'horse', '75', '827', '3', '1010'],
 ['image_18 (7).jpg', '1024', '684', 'person', '311', '546', '73', '344'],
 ['image_18 (7).jpg', '1024', '684', 'car', '84', '909', '221', '577'],
 ['image_18 (8).jpg', '1024', '768', 'sofa', '71', '936', '108', '660'],
 ['image_18.jpg', '682', '1023', 'person', '284', '531', '256', '594'],
 ['image_18.jpg', '682', '1023', 'cycle', '130', '486', '454', '737'],
 ['image_19 (2).jpg', '787', '1024', 'bottle', '57', '430', '65', '864'],
 ['image_19 (2).jpg', '787', '1024', 'bottle', '430', '744', '86', '887'],
 ['image_19 (3).jpg', '800', '600', 'bus', '7', '792', '66', '505'],
 ['image_19 (6).jpg', '1024', '683', 'horse', '493', '927', '179', '566'],
 ['image_19 (7).jpg', '1024', '683', 'car', '108', '154', '450', '495'],
 ['image_2 (2).jpg', '1024', '768', 'bottle', '260', '509', '157', '587'],
 ['image_2 (2).jpg', '1024', '768', 'bottle', '542', '795', '136', '581'],
 ['image_2 (4).jpg', '685', '1023', 'chair', '282', '665', '205', '964'],
 ['image_2 (5).jpg', '1024', '682', 'horse', '273', '1024', '78', '682'],
 ['image_2 (6).jpg', '683', '1024', 'person', '201', '542', '40', '720'],
 ['image_2 (7).jpg', '1024', '768', 'sofa', '13', '791', '183', '759'],
 ['image_2 (7).jpg', '1024', '768', 'plant', '863', '1024', '164', '544'],
 ['image_2 (8).jpg', '1024', '1024', 'chair', '12', '398', '473', '1005'],
 ['image_2 (8).jpg', '1024', '1024', 'chair', '422', '820', '485', '989'],
 ['image_2 (8).jpg', '1024', '1024', 'chair', '817', '996', '419', '876'],
 ['image_2 (8).jpg', '1024', '1024', 'glass', '305', '372', '312', '483'],
 ['image_2 (8).jpg', '1024', '1024', 'table', '18', '1004', '295', '941'],
 ['image_2.jpg', '1024', '683', 'bird', '427', '708', '217', '508'],
 ['image_20 (2).jpg', '595', '1024', 'bottle', '175', '425', '4', '1003'],
 ['image_20 (3).jpg', '1000', '750', 'bus', '41', '750', '226', '634'],
 ['image_20 (4).jpg', '800', '533', 'car', '62', '719', '105', '447'],
 ['image_20 (5).jpg', '768', '1024', 'chair', '79', '629', '20', '978'],
 ['image_20 (6).jpg', '1024', '768', 'horse', '35', '890', '81', '645'],
 ['image_20 (8).jpg', '1024', '768', 'sofa', '9', '1000', '177', '724'],
 ['image_20.jpg', '1024', '683', 'person', '638', '789', '220', '660'],
 ['image_21 (3).jpg', '1024', '576', 'bus', '196', '851', '111', '494'],
 ['image_21 (4).jpg', '1024', '683', 'car', '101', '901', '172', '617'],
 ['image_21 (4).jpg', '1024', '683', 'person', '1', '81', '208', '519'],
 ['image_21 (5).jpg', '532', '800', 'chair', '68', '516', '12', '800'],
 ['image_21 (6).jpg', '1024', '683', 'person', '525', '657', '93', '326'],
 ['image_21 (6).jpg', '1024', '683', 'horse', '365', '819', '102', '560'],
 ['image_21 (6).jpg', '1024', '683', 'car', '806', '1024', '204', '449'],
 ['image_21 (7).jpg', '1024', '683', 'person', '382', '612', '41', '490'],
 ['image_21 (7).jpg', '1024', '683', 'cycle', '288', '777', '321', '680'],
 ['image_21 (8).jpg', '1024', '768', 'sofa', '1', '1024', '172', '656'],
 ['image_21.jpg', '1024', '576', 'cycle', '566', '987', '101', '420'],
 ['image_22 (2).jpg', '635', '1024', 'bottle', '157', '491', '6', '1017'],
 ['image_22 (3).jpg', '1024', '576', 'bus', '214', '775', '39', '543'],
 ['image_22 (4).jpg', '1024', '768', 'car', '97', '882', '145', '641'],
 ['image_22 (5).jpg', '613', '1023', 'chair', '81', '557', '5', '983'],
 ['image_22 (6).jpg', '1024', '681', 'horse', '4', '972', '14', '675'],
 ['image_22 (7).jpg', '683', '1024', 'person', '139', '379', '240', '784'],
 ['image_22 (8).jpg', '1024', '572', 'person', '40', '995', '86', '362'],
 ['image_22 (8).jpg', '1024', '572', 'sofa', '3', '1023', '13', '546'],
 ['image_22.jpg', '1024', '605', 'cycle', '614', '868', '413', '563'],
 ['image_23 (2).jpg', '681', '1024', 'bottle', '22', '329', '63', '932'],
 ['image_23 (2).jpg', '681', '1024', 'bottle', '338', '649', '164', '955'],
 ['image_23 (3).jpg', '1024', '768', 'bus', '1', '997', '239', '756'],
 ['image_23 (4).jpg', '1024', '683', 'car', '275', '807', '184', '665'],
 ['image_23 (5).jpg', '1024', '768', 'chair', '186', '746', '19', '766'],
 ['image_23 (6).jpg', '1024', '683', 'horse', '81', '627', '17', '683'],
 ['image_23 (7).jpg', '1024', '790', 'car', '36', '778', '192', '786'],
 ['image_23 (7).jpg', '1024', '790', 'person', '876', '977', '319', '605'],
 ['image_23 (8).jpg', '1024', '768', 'sofa', '25', '1024', '94', '593'],
 ['image_23.jpg', '1024', '683', 'person', '304', '825', '79', '683'],
 ['image_23.jpg', '1024', '683', 'bottle', '860', '935', '327', '476'],
 ['image_24 (2).jpg', '1024', '683', 'bottle', '362', '612', '59', '641'],
 ['image_24 (2).jpg', '1024', '683', 'bottle', '362', '612', '59', '641'],
 ['image_24 (3).jpg', '1024', '682', 'bus', '360', '882', '52', '626'],
 ['image_24 (3).jpg', '1024', '682', 'bus', '360', '882', '52', '626'],
 ['image_24 (5).jpg', '680', '1024', 'chair', '120', '598', '191', '884'],
 ['image_24 (5).jpg', '680', '1024', 'chair', '120', '598', '191', '884'],
 ['image_24 (6).jpg', '1024', '680', 'horse', '341', '1024', '28', '680'],
 ['image_24 (6).jpg', '1024', '680', 'horse', '341', '1024', '28', '680'],
 ['image_24 (7).jpg', '1024', '660', 'person', '407', '629', '53', '660'],
 ['image_24 (7).jpg', '1024', '660', 'person', '407', '629', '53', '660'],
 ['image_24 (8).jpg', '1024', '768', 'sofa', '1', '1024', '60', '529'],
 ['image_24 (8).jpg', '1024', '768', 'sofa', '1', '1024', '60', '529']]

In [8]:
df = pd.DataFrame(data,columns = ['filename','width','height','name','xmin','xmax','ymin','ymax'])
df

             filename width height    name xmin  xmax ymin ymax
0    image_31 (6).jpg  1024    768   horse  252   757  148  636
1     image_1 (2).jpg  1024    819  bottle  250   467   65  819
2     image_1 (2).jpg  1024    819  bottle  546   748   60  791
3     image_1 (2).jpg  1024    819  bottle  444   614  190  812
4     image_1 (3).jpg  1024    682     bus   54   994   59  548
..                ...   ...    ...     ...  ...   ...  ...  ...
147  image_24 (6).jpg  1024    680   horse  341  1024   28  680
148  image_24 (7).jpg  1024    660  person  407   629   53  660
149  image_24 (7).jpg  1024    660  person  407   629   53  660
150  image_24 (8).jpg  1024    768    sofa    1  1024   60  529
151  image_24 (8).jpg  1024    768    sofa    1  1024   60  529

[152 rows x 8 columns]

In [9]:
df.head()

           filename width height    name xmin xmax ymin ymax
0  image_31 (6).jpg  1024    768   horse  252  757  148  636
1   image_1 (2).jpg  1024    819  bottle  250  467   65  819
2   image_1 (2).jpg  1024    819  bottle  546  748   60  791
3   image_1 (2).jpg  1024    819  bottle  444  614  190  812
4   image_1 (3).jpg  1024    682     bus   54  994   59  548

In [10]:
df.shape

(152, 8)

In [11]:
df['name'].value_counts()

name
person    28
bottle    23
horse     20
chair     19
bus       17
sofa      17
car       13
cycle      6
table      4
bird       3
plant      1
glass      1
Name: count, dtype: int64

In [12]:
df.dtypes

filename    object
width       object
height      object
name        object
xmin        object
xmax        object
ymin        object
ymax        object
dtype: object

# conversion

In [13]:
# type conversion
cols = ['width','height','xmin','xmax','ymin','ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  152 non-null    object
 1   width     152 non-null    int64
 2   height    152 non-null    int64
 3   name      152 non-null    object
 4   xmin      152 non-null    int64
 5   xmax      152 non-null    int64
 6   ymin      152 non-null    int64
 7   ymax      152 non-null    int64
dtypes: int64(6), object(2)
memory usage: 9.6+ KB

In [14]:
# center x, center y
df['center_x'] = ((df['xmax']+df['xmin'])/2)/df['width']
df['center_y'] = ((df['ymax']+df['ymin'])/2)/df['height']
# w 
df['w'] = (df['xmax']-df['xmin'])/df['width']
# h 
df['h'] = (df['ymax']-df['ymin'])/df['height']

In [15]:
df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,image_31 (6).jpg,1024,768,horse,252,757,148,636,0.492676,0.510417,0.493164,0.635417
1,image_1 (2).jpg,1024,819,bottle,250,467,65,819,0.350098,0.539683,0.211914,0.920635
2,image_1 (2).jpg,1024,819,bottle,546,748,60,791,0.631836,0.519536,0.197266,0.892552
3,image_1 (2).jpg,1024,819,bottle,444,614,190,812,0.516602,0.611722,0.166016,0.759463
4,image_1 (3).jpg,1024,682,bus,54,994,59,548,0.511719,0.445015,0.917969,0.717009

In [16]:
# label encoding4
def label_encoding(x):
    labels = {'person':0, 'car':1, 'chair':2, 'bottle':3, 'bird':4,
              'sofa':5, 'cycle':6, 'horse':7, 'bus':8}
    try:
        return labels[x]
    except KeyError:
        # Handle cases where 'x' is not found in the labels dictionary
        return -1  # Or any other appropriate value or action
df['id'] = df['name'].apply(label_encoding)
df

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
0,image_31 (6).jpg,1024,768,horse,252,757,148,636,0.492676,0.510417,0.493164,0.635417,7
1,image_1 (2).jpg,1024,819,bottle,250,467,65,819,0.350098,0.539683,0.211914,0.920635,3
2,image_1 (2).jpg,1024,819,bottle,546,748,60,791,0.631836,0.519536,0.197266,0.892552,3
3,image_1 (2).jpg,1024,819,bottle,444,614,190,812,0.516602,0.611722,0.166016,0.759463,3
4,image_1 (3).jpg,1024,682,bus,54,994,59,548,0.511719,0.445015,0.917969,0.717009,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,image_24 (6).jpg,1024,680,horse,341,1024,28,680,0.666504,0.520588,0.666992,0.958824,7
148,image_24 (7).jpg,1024,660,person,407,629,53,660,0.505859,0.540152,0.216797,0.919697,0
149,image_24 (7).jpg,1024,660,person,407,629,53,660,0.505859,0.540152,0.216797,0.919697,0
150,image_24 (8).jpg,1024,768,sofa,1,1024,60,529,0.500488,0.383464,0.999023,0.610677,5
151,image_24 (8).jpg,1024,768,sofa,1,1024,60,529,0.500488,0.383464,0.999023,0.610677,5

### split data into train and test

In [17]:
images = df['filename'].unique()

In [18]:
len(images)

110

In [19]:
# 80% train and 20% test
img_df = pd.DataFrame(images,columns=['filename'])
img_train = tuple(img_df.sample(frac=0.8)['filename']) # shuffle and pick 80% of images

In [20]:
img_test = tuple(img_df.query(f'filename not in {img_train}')['filename']) # take rest 20% images

In [21]:
len(img_train), len(img_test)

(88, 22)

In [22]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [23]:
train_df

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
0,image_31 (6).jpg,1024,768,horse,252,757,148,636,0.492676,0.510417,0.493164,0.635417,7
1,image_1 (2).jpg,1024,819,bottle,250,467,65,819,0.350098,0.539683,0.211914,0.920635,3
2,image_1 (2).jpg,1024,819,bottle,546,748,60,791,0.631836,0.519536,0.197266,0.892552,3
3,image_1 (2).jpg,1024,819,bottle,444,614,190,812,0.516602,0.611722,0.166016,0.759463,3
4,image_1 (3).jpg,1024,682,bus,54,994,59,548,0.511719,0.445015,0.917969,0.717009,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,image_24 (3).jpg,1024,682,bus,360,882,52,626,0.606445,0.497067,0.509766,0.841642,8
146,image_24 (6).jpg,1024,680,horse,341,1024,28,680,0.666504,0.520588,0.666992,0.958824,7
147,image_24 (6).jpg,1024,680,horse,341,1024,28,680,0.666504,0.520588,0.666992,0.958824,7
148,image_24 (7).jpg,1024,660,person,407,629,53,660,0.505859,0.540152,0.216797,0.919697,0
149,image_24 (7).jpg,1024,660,person,407,629,53,660,0.505859,0.540152,0.216797,0.919697,0

In [24]:
test_df

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
6,image_1 (6).jpg,1024,683,person,181,492,75,504,0.328613,0.423865,0.303711,0.628111,0
7,image_1 (6).jpg,1024,683,person,627,984,59,446,0.786621,0.369693,0.348633,0.566618,0
21,image_11 (3).jpg,1024,768,bus,2,778,203,631,0.380859,0.542969,0.757812,0.557292,8
37,image_13 (4).jpg,683,1024,chair,107,609,39,983,0.524158,0.499023,0.734993,0.921875,2
44,image_14 (5).jpg,314,523,table,12,299,16,518,0.495223,0.510516,0.914013,0.959847,-1
50,image_15 (4).jpg,866,577,car,382,866,68,576,0.720554,0.558059,0.558891,0.880416,1
52,image_15 (6).jpg,1024,700,horse,3,582,53,671,0.285645,0.517143,0.565430,0.882857,7
53,image_15 (6).jpg,1024,700,horse,526,1006,59,633,0.748047,0.494286,0.468750,0.820000,7
59,image_16 (6).jpg,683,1024,horse,4,567,119,869,0.418009,0.482422,0.824305,0.732422,7
69,image_17 (6).jpg,200,150,horse,4,189,6,140,0.482500,0.486667,0.925000,0.893333,7
70,image_17 (7).jpg,1024,1024,person,216,327,419,670,0.265137,0.531738,0.108398,0.245117,0
71,image_17 (7).jpg,1024,1024,person,334,424,459,659,0.370117,0.545898,0.087891,0.195312,0
74,image_18 (2).jpg,680,1024,bottle,118,547,67,994,0.488971,0.518066,0.630882,0.905273,3
81,image_18 (8).jpg,1024,768,sofa,71,936,108,660,0.491699,0.500000,0.844727,0.718750,5
91,image_2 (4).jpg,685,1023,chair,282,665,205,964,0.691241,0.571359,0.559124,0.741935,2
104,image_20 (4).jpg,800,533,car,62,719,105,447,0.488125,0.517824,0.821250,0.641651,1
106,image_20 (6).jpg,1024,768,horse,35,890,81,645,0.451660,0.472656,0.834961,0.734375,7
118,image_21 (8).jpg,1024,768,sofa,1,1024,172,656,0.500488,0.539062,0.999023,0.630208,5
122,image_22 (4).jpg,1024,768,car,97,882,145,641,0.478027,0.511719,0.766602,0.645833,1
126,image_22 (8).jpg,1024,572,person,40,995,86,362,0.505371,0.391608,0.932617,0.482517,0
127,image_22 (8).jpg,1024,572,sofa,3,1023,13,546,0.500977,0.488636,0.996094,0.931818,5
129,image_23 (2).jpg,681,1024,bottle,22,329,63,932,0.257709,0.485840,0.450808,0.848633,3
130,image_23 (2).jpg,681,1024,bottle,338,649,164,955,0.724670,0.546387,0.456681,0.772461,3
135,image_23 (7).jpg,1024,790,car,36,778,192,786,0.397461,0.618987,0.724609,0.751899,1
136,image_23 (7).jpg,1024,790,person,876,977,319,605,0.904785,0.584810,0.098633,0.362025,0
140,image_24 (2).jpg,1024,683,bottle,362,612,59,641,0.475586,0.512445,0.244141,0.852123,3
141,image_24 (2).jpg,1024,683,bottle,362,612,59,641,0.475586,0.512445,0.244141,0.852123,3
144,image_24 (5).jpg,680,1024,chair,120,598,191,884,0.527941,0.524902,0.702941,0.676758,2
145,image_24 (5).jpg,680,1024,chair,120,598,191,884,0.527941,0.524902,0.702941,0.676758,2
150,image_24 (8).jpg,1024,768,sofa,1,1024,60,529,0.500488,0.383464,0.999023,0.610677,5
151,image_24 (8).jpg,1024,768,sofa,1,1024,60,529,0.500488,0.383464,0.999023,0.610677,5

In [25]:
### Assign id number to object names

In [26]:
test_df.head(10)

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
6,image_1 (6).jpg,1024,683,person,181,492,75,504,0.328613,0.423865,0.303711,0.628111,0
7,image_1 (6).jpg,1024,683,person,627,984,59,446,0.786621,0.369693,0.348633,0.566618,0
21,image_11 (3).jpg,1024,768,bus,2,778,203,631,0.380859,0.542969,0.757812,0.557292,8
37,image_13 (4).jpg,683,1024,chair,107,609,39,983,0.524158,0.499023,0.734993,0.921875,2
44,image_14 (5).jpg,314,523,table,12,299,16,518,0.495223,0.510516,0.914013,0.959847,-1
50,image_15 (4).jpg,866,577,car,382,866,68,576,0.720554,0.558059,0.558891,0.880416,1
52,image_15 (6).jpg,1024,700,horse,3,582,53,671,0.285645,0.517143,0.565430,0.882857,7
53,image_15 (6).jpg,1024,700,horse,526,1006,59,633,0.748047,0.494286,0.468750,0.820000,7
59,image_16 (6).jpg,683,1024,horse,4,567,119,869,0.418009,0.482422,0.824305,0.732422,7
69,image_17 (6).jpg,200,150,horse,4,189,6,140,0.482500,0.486667,0.925000,0.893333,7

### Save Image and Labels in text

In [27]:
import os
from shutil import move

In [28]:

cols = ['filename','id','center_x','center_y', 'w', 'h']
groupby_obj_train = train_df[cols].groupby('filename')
groupby_obj_test = test_df[cols].groupby('filename')

In [29]:
import os
import shutil
import glob
import pandas as pd

# Function to save data (both images and labels)
def save_data(filename, folder_path, group_obj):
    # Normalize the filename (remove spaces, convert to lowercase, etc.)
    normalized_filename = os.path.splitext(filename)[0].strip().lower()
    
    # Find matching image files (handles multiple extensions like .jpg, .jpeg, .png, etc.)
    matches = glob.glob(f"data_images/{normalized_filename}.*")  # Matches any extension
    
    if matches:
        src_path = matches[0]  # Pick the first matching file
        dst_path = os.path.join(folder_path, os.path.basename(src_path))
        
        # Check if the source file exists before moving
        if os.path.exists(src_path):
            print(f"Moving {src_path} -> {dst_path}")  # Debugging statement
            shutil.move(src_path, dst_path)
        else:
            print(f"Source file does not exist: {src_path}")
    else:
        print(f"No matching image file found for: {filename}")
    
    # Save the labels as a text file if the filename exists in the group object
    if filename in group_obj.groups:
        text_filename = os.path.join(folder_path, os.path.splitext(filename)[0] + '.txt')
        group_data = group_obj.get_group(filename).set_index('filename')
        group_data.to_csv(text_filename, sep=' ', index=False, header=False)
    else:
        print(f"Filename not found in group object: {filename}")

# Ensure the directories exist
train_folder = 'data_images/train'
test_folder = 'data_images/test'
os.makedirs(train_folder, exist_ok=True)
os.makedirs(test_folder, exist_ok=True)

# Apply the function to training filenames
filename_series_train = pd.Series(groupby_obj_train.groups.keys())
filename_series_train.apply(lambda filename: save_data(filename, train_folder, groupby_obj_train))

# Apply the function to test filenames
filename_series_test = pd.Series(groupby_obj_test.groups.keys())
filename_series_test.apply(lambda filename: save_data(filename, test_folder, groupby_obj_test))

Moving data_images\image_1 (2).xml -> data_images/train\image_1 (2).xml
Moving data_images\image_1 (3).xml -> data_images/train\image_1 (3).xml
Moving data_images\image_1 (5).xml -> data_images/train\image_1 (5).xml
Moving data_images\image_1 (7).xml -> data_images/train\image_1 (7).xml
Moving data_images\image_1 (8).xml -> data_images/train\image_1 (8).xml
Moving data_images\image_1.xml -> data_images/train\image_1.xml
Moving data_images\image_10 (3).xml -> data_images/train\image_10 (3).xml
Moving data_images\image_10 (4).xml -> data_images/train\image_10 (4).xml
Moving data_images\image_10 (5).xml -> data_images/train\image_10 (5).xml
Moving data_images\image_10 (6).xml -> data_images/train\image_10 (6).xml
Moving data_images\image_10 (7).xml -> data_images/train\image_10 (7).xml
Moving data_images\image_10 (8).xml -> data_images/train\image_10 (8).xml
Moving data_images\image_10.xml -> data_images/train\image_10.xml
Moving data_images\image_11 (2).xml -> data_images/train\image_11 (2).xml
Moving data_images\image_11 (4).xml -> data_images/train\image_11 (4).xml

Moving data_images\image_11 (5).xml -> data_images/train\image_11 (5).xml
Moving data_images\image_11 (6).xml -> data_images/train\image_11 (6).xml
Moving data_images\image_11 (7).xml -> data_images/train\image_11 (7).xml
Moving data_images\image_11.xml -> data_images/train\image_11.xml
Moving data_images\image_12 (2).xml -> data_images/train\image_12 (2).xml
Moving data_images\image_12 (4).xml -> data_images/train\image_12 (4).xml
Moving data_images\image_12 (5).xml -> data_images/train\image_12 (5).xml
Moving data_images\image_12 (6).xml -> data_images/train\image_12 (6).xml
Moving data_images\image_12 (7).xml -> data_images/train\image_12 (7).xml
Moving data_images\image_13 (3).xml -> data_images/train\image_13 (3).xml
Moving data_images\image_13 (7).xml -> data_images/train\image_13 (7).xml
Moving data_images\image_14 (2).xml -> data_images/train\image_14 (2).xml
Moving data_images\image_14 (3).xml -> data_images/train\image_14 (3).xml
Moving data_images\image_14 (4).xml -> data_images/train\image_14 (4).xml
Moving data_images\image_14 (6).xml -> data_images/train\image_14 (6).xml
Moving data_images\image_14.xml -> data_images/train\image_14.xml
Moving data_images\image_15 (3).xml -> data_images/train\image_15 (3).xml
Moving data_images\image_15 (5).xml -> data_images/train\image_15 (5).xml
Moving data_images\image_15 (7).xml -> data_images/train\image_15 (7).xml
Moving data_images\image_16 (3).xml -> data_images/train\image_16 (3).xml
Moving data_images\image_16 (4).xml -> data_images/train\image_16 (4).xml
Moving data_images\image_16 (5).xml -> data_images/train\image_16 (5).xml
Moving data_images\image_16 (8).xml -> data_images/train\image_16 (8).xml
Moving data_images\image_16.xml -> data_images/train\image_16.xml
Moving data_images\image_17 (2).xml -> data_images/train\image_17 (2).xml
Moving data_images\image_17 (3).xml -> data_images/train\image_17 (3).xml
Moving data_images\image_17 (4).xml -> data_images/train\image_17 (4).xml
Moving data_images\image_17 (5).xml -> data_images/train\image_17 (5).xml
Moving data_images\image_17 (8).xml -> data_images/train\image_17 (8).xml
Moving data_images\image_17.xml -> data_images/train\image_17.xml
Moving data_images\image_18 (3).xml -> data_images/train\image_18 (3).xml
Moving data_images\image_18 (4).xml -> data_images/train\image_18 (4).xml
Moving data_images\image_18 (5).xml -> data_images/train\image_18 (5).xml
Moving data_images\image_18 (6).xml -> data_images/train\image_18 (6).xml
Moving data_images\image_18 (7).xml -> data_images/train\image_18 (7).xml
Moving data_images\image_18.xml -> data_images/train\image_18.xml
Moving data_images\image_19 (2).xml -> data_images/train\image_19 (2).xml
Moving data_images\image_19 (3).xml -> data_images/train\image_19 (3).xml
Moving data_images\image_19 (6).xml -> data_images/train\image_19 (6).xml
Moving data_images\image_19 (7).xml -> data_images/train\image_19 (7).xml
Moving data_images\image_2 (2).xml -> data_images/train\image_2 (2).xml
Moving data_images\image_2 (5).xml -> data_images/train\image_2 (5).xml
Moving data_images\image_2 (6).xml -> data_images/train\image_2 (6).xml
Moving data_images\image_2 (7).xml -> data_images/train\image_2 (7).xml
Moving data_images\image_2 (8).xml -> data_images/train\image_2 (8).xml
Moving data_images\image_2.xml -> data_images/train\image_2.xml
Moving data_images\image_20 (2).xml -> data_images/train\image_20 (2).xml
Moving data_images\image_20 (3).xml -> data_images/train\image_20 (3).xml
Moving data_images\image_20 (5).xml -> data_images/train\image_20 (5).xml
Moving data_images\image_20 (8).xml -> data_images/train\image_20 (8).xml
Moving data_images\image_20.xml -> data_images/train\image_20.xml
Moving data_images\image_21 (3).xml -> data_images/train\image_21 (3).xml
Moving data_images\image_21 (4).xml -> data_images/train\image_21 (4).xml
Moving data_images\image_21 (5).xml -> data_images/train\image_21 (5).xml
Moving data_images\image_21 (6).xml -> data_images/train\image_21 (6).xml
Moving data_images\image_21 (7).xml -> data_images/train\image_21 (7).xml
Moving data_images\image_21.xml -> data_images/train\image_21.xml
Moving data_images\image_22 (2).xml -> data_images/train\image_22 (2).xml
Moving data_images\image_22 (3).xml -> data_images/train\image_22 (3).xml
Moving data_images\image_22 (5).xml -> data_images/train\image_22 (5).xml
Moving data_images\image_22 (6).xml -> data_images/train\image_22 (6).xml
Moving data_images\image_22 (7).xml -> data_images/train\image_22 (7).xml
Moving data_images\image_22.xml -> data_images/train\image_22.xml
Moving data_images\image_23 (3).xml -> data_images/train\image_23 (3).xml
Moving data_images\image_23 (4).xml -> data_images/train\image_23 (4).xml
Moving data_images\image_23 (5).xml -> data_images/train\image_23 (5).xml
Moving data_images\image_23 (6).xml -> data_images/train\image_23 (6).xml
Moving data_images\image_23 (8).xml -> data_images/train\image_23 (8).xml
Moving data_images\image_23.xml -> data_images/train\image_23.xml
Moving data_images\image_24 (3).xml -> data_images/train\image_24 (3).xml
Moving data_images\image_24 (6).xml -> data_images/train\image_24 (6).xml
Moving data_images\image_24 (7).xml -> data_images/train\image_24 (7).xml
No matching image file found for: image_31 (6).jpg
Moving data_images\image_1 (6).xml -> data_images/test\image_1 (6).xml
Moving data_images\image_11 (3).xml -> data_images/test\image_11 (3).xml
Moving data_images\image_13 (4).xml -> data_images/test\image_13 (4).xml
Moving data_images\image_14 (5).xml -> data_images/test\image_14 (5).xml
Moving data_images\image_15 (4).xml -> data_images/test\image_15 (4).xml
Moving data_images\image_15 (6).xml -> data_images/test\image_15 (6).xml
Moving data_images\image_16 (6).xml -> data_images/test\image_16 (6).xml
Moving data_images\image_17 (6).xml -> data_images/test\image_17 (6).xml
Moving data_images\image_17 (7).xml -> data_images/test\image_17 (7).xml
Moving data_images\image_18 (2).xml -> data_images/test\image_18 (2).xml
Moving data_images\image_18 (8).xml -> data_images/test\image_18 (8).xml
Moving data_images\image_2 (4).xml -> data_images/test\image_2 (4).xml
Moving data_images\image_20 (4).xml -> data_images/test\image_20 (4).xml
Moving data_images\image_20 (6).xml -> data_images/test\image_20 (6).xml
Moving data_images\image_21 (8).xml -> data_images/test\image_21 (8).xml
Moving data_images\image_22 (4).xml -> data_images/test\image_22 (4).xml
Moving data_images\image_22 (8).xml -> data_images/test\image_22 (8).xml
Moving data_images\image_23 (2).xml -> data_images/test\image_23 (2).xml
Moving data_images\image_23 (7).xml -> data_images/test\image_23 (7).xml
Moving data_images\image_24 (2).xml -> data_images/test\image_24 (2).xml
Moving data_images\image_24 (5).xml -> data_images/test\image_24 (5).xml
Moving data_images\image_24 (8).xml -> data_images/test\image_24 (8).xml

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
dtype: object